### PR TITLE
Fix tests failing due to file location

### LINKED ISSUE #20: Some tests fail if pytest is run in root folder
Example of failure:
```
_______________________________________ test_exhaustive_template_is_isomorphic ________________________________________

    def test_exhaustive_template_is_isomorphic():
>       g1 = Graph().parse("043_exhaustive_example_perfect_output.ttl")

tests\test_template043.py:43:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.venv\lib\site-packages\rdflib\graph.py:1234: in parse
    source = create_input_source(
.venv\lib\site-packages\rdflib\parser.py:326: in create_input_source
    ) = _create_input_source_from_location(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

file = None, format = None, input_source = None, location = '043_exhaustive_example_perfect_output.ttl'

    def _create_input_source_from_location(file, format, input_source, location):
        # Fix for Windows problem https://github.com/RDFLib/rdflib/issues/145 and
        # https://github.com/RDFLib/rdflib/issues/1430
        # NOTE: using pathlib.Path.exists on a URL fails on windows as it is not a
        # valid path. However os.path.exists() returns false for a URL on windows
        # which is why it is being used instead.
        if os.path.exists(location):
            location = pathlib.Path(location).absolute().as_uri()

        base = pathlib.Path.cwd().as_uri()

        absolute_location = URIRef(location, base=base)

        if absolute_location.startswith("file:///"):
            filename = url2pathname(absolute_location.replace("file:///", "/"))
>           file = open(filename, "rb")
E           FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dlinke\\MyProg_exp040\\043_exhaustive_example_perfect_output.ttl'

.venv\lib\site-packages\rdflib\parser.py:373: FileNotFoundError
```
I'll send a PR with a fix.

### PR DESCRIPTION
**Pull request by dalito**
Closes #20

### CODE REVIEW

**Comment by dalito** [comment]
I also saw another problem: `sys.path.append(str(Path(__file__).parent.parent.absolute()))` may not work as intended since `__file__` is not always giving an absolute file location. `Path(".").parent` is just `"."`. So it is better to write `sys.path.append(str(Path(__file__).absolute().parent.parent))`. If you want I can add this change to the PR.

**Comment by peterphilips** [comment]
@dalito , thanks for picking that up - @nicholascar  will most likely review and confirm changes

**Comment by nicholascar** [comment]
Thanks @dalito for identifying, and fixing, this issue! I'll merge the changes in, in just a second.

How did you come across this project by the way? We are thrilled to have external people interested in the tool.

**Comment by dalito** [comment]
@nicholascar - I found your announcement for VocExcel either in the rdflib google.news group or in an RDA forum via google. I searched for tools to create SKOS vocabularies and are usable by people that do not know o want to learn turtle, rdf etc..

We found VocExcel for the first time in Aug-2021 and started to use it more in Dec-2021. In [NFDI4Cat](https://nfdi4cat.org/en/) VocExcel eases contributions to the vocabularies by non-data experts. The main work is done in closed repos but I may send some small PRs in the future.

**Comment by nicholascar** [comment]
Thanks for the background info @dalito! We are using VocExcel for a number of projects so active development is on-going. We are really happy to hear of your interests and accept requests as Issues in this repo, or Pull Requests of course!

Just so you know: we will re-implement the reverse conversion - RDF to Excel - for the new style templates soon. We'll also add the ability to read from Google Sheets instead of Excel and we'll add an option to the Command Line tool to turn on SHACL validation for outputs in the case of conversion errors.

**Comment by dalito** [comment]
Great! The reverse conversion RDF -> Excel would be very useful for us, too.

**Pull request merged**
